### ISSUE TITLE
[Feature Request] How about making End-to-End Encryption possible.

### ISSUE THREAD

**Issue by xg590** [TudbuT/qft#10]
Hi Daniel, I found your tool exceptionally useful. 

I have analyzed the packets using wireshark and found they are transferred in plaintext, which is not ideal for me to send personal files. "croc" has the E2E feature so I want to get something similar. 

One solution is adding stdin/stdout features to "qft" so I can come up some schemes that feed "qft" with encrypted data as stdin.

* sender
```
encrypt privatePhoto.png | qft sender my.server:12345 abcdefg -stdin - 1111
```
* receiver
```
qft receiver my.server:12345 abcdefg -stdout 1111 | decrypt - > privatePhoto.png 
```

Best,
Xiaokang

**Comment by TudbuT** [comment]
Hey, thanks for reaching out!

I should probably clarify this in the readme: using /dev/stdin and /dev/stdout as files is perfectly possible, so you can actually stream:
- sender:
  ```
  encrypt privatePhoto.png | qft sender tudbut.de:4277 cool_key /dev/stdin 1000
  ```
- receiver:
  ```
  qft receiver tudbut.de:4277 cool_key /dev/stdout 1000 | decrypt > privatePhoto.png
  ```

Best wishes,
Daniel

**Comment by xg590** [comment]
Tried this but failed
* Sender
```
$ cat test.txt | qft sender my.server:54321 cool_key /dev/stdin 1000
Holepunching xxx.xxx.xxx.xxx:49026 (partner) and :33496 (you).
Connecting...
Holepunch and connection successful.
Length: 0
Sent 240000 bytes; Speed: 125 kb/s
10s passed since last packet ==> Contact broke. Trying to resend packet...
```
* Receiver
```
[xg590@broyde ~]$ ./bin/qft receiver my.server:54321 cool_key /dev/stdout 1000 | cat
Holepunching xxx.xxx.xxx.xxx:49340 (partner) and :49026 (you).
Connecting...
Holepunch and connection successful.
thread 'main' panicked at 'unable to set file length: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/main.rs:467:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by TudbuT** [comment]
Oops, guess I broke it when i added file length transmission. I'll fix it shortly.

**Comment by xg590** [comment]
> Oops, guess I broke it when i added file length transmission. I'll fix it shortly.

BTW, I have a small suggestion that you can release the qft came from a static build. I failed to run qft in Ubuntu 20.04 and CentOS because both comes with glibc<2.33. I learned the basics of Rust and got my statically built qft.

**Comment by TudbuT** [comment]
Oh, is ubuntu still on that old glibc? How did you fix the issue?

**Comment by xg590** [comment]
> Oh, is ubuntu still on that old glibc? How did you fix the issue?

I use Ubuntu 2204 on my personal machine, which use GLIBC 2.35. But I manage several servers, which runs CentOS 7.9 (GLIBC 2.17) and Ubuntu 2004 (GLIBC 2.31). Unfortunately, I cannot upgrade these OSes so I have to compile qft myself. 

I downloaded the qft and built it with
```
wget https://github.com/TudbuT/qft/archive/refs/heads/nogui.zip
unzip nogui.zip
cd qft-nogui/
RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
ldd target/x86_64-unknown-linux-gnu/release/qft
```

**Comment by TudbuT** [comment]
Thanks, I'll release a static one soon.

**Comment by xg590** [comment]
I will write a Python wrapper to do the end-to-end encryption (E2EE) part. I would like to hear you comments.

1. Open a file
2. Read 200 bytes data (chop the file in chucks)
3. Encrypt it  
4. Feed the encrypted data through pipe to qft
5. Send the encrypted data over the p2p link 
6. Redirect to Python and decrypt it
7. Goto step 2 if the file is larger than 200 bytes.
8. Check MAC and save it.

* I tried encrypt and decrypt a 3 GB file on an Intel Celeron CPU. It only takes 3 minutes. ChaCha20_Poly1305 is amazing.

* This is might be a dumb question. Is there an optimal size for the data to be fed to qft. Do I need to worry about the chuck size of the encrypted data. If I feed qft with 100 bytes each time, will it be send immediately, or wait for another 100 bytes before the sending (I saw the source code, it seems like the buffer size is 200 bytes).

**Comment by TudbuT** [comment]
This isn't a trivial or dumb question.

There is no optimal size. QFT's read speed is mostly bottlenecked by the network module, as it will always wait a millisecond for potential incoming packets after sending a packet. There is also no deterministic buffer size (only in the network module). The buffer size is determined by the lsst argument, and qft will always dynamically choose the fastest way when it can decide between reading the whole buffer and reading only some part of it. Usually, the two are essentially the same due to the network module bottleneck.

**Comment by xg590** [comment]
Recompiled, tested, it works beautifully.
