### ISSUE TITLE
cannot send files

### ISSUE THREAD

**Issue by MaoHolden** [TudbuT/qft#15]
Hey, i tried to use but couldn't make it work, and get this error on Fedora Linux

```bash
$ ./qft 
thread '<unnamed>' panicked at 'unable to receive from helper: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }', src/main.rs:563:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

![Screenshot from 2023-10-29 21-24-52](https://github.com/TudbuT/qft/assets/135930538/435a652f-c010-4165-856b-081c2d0cdb2b)

I tried sending from windows/starlink to linux/regular-internet-tru-vpn
Since I was not able to do it then I tried 
from windows/starlink to windows/regular-internet (no vpn) 
but also did not work :( 

not an expert in networking so that's as far as I can report

**Comment by TudbuT** [comment]
Looks like the helper may be down. I'll check that out.

**Comment by TudbuT** [comment]
That should be fixed now, it appears my server restarted and the qft service didn't start up correctly.
