### ISSUE TITLE
Is it possible to transfer directories?

### ISSUE THREAD

**Issue by altefwan** [TudbuT/qft#19]
I know I can just zip the folder quickly then transfer it, but in some cases where the storage space is really limited for the receiver, the receiver cannot extract the received zip file due to lack of storage space.

**Comment by TudbuT** [comment]
You can use tar with streaming for this purpose:
`tar -cv . | QFT_STREAM=1 qft ... /dev/stdin`
and on the other side:
`qft ... /dev/stdout | tar -xv`

**Comment by altefwan** [comment]
anyway to do this in windows?

**Comment by TudbuT** [comment]
@altefwan 
[tar for windows](https://gnuwin32.sourceforge.net/packages/gtar.htm)

**Comment by TudbuT** [comment]
im not sure about the /dev/ pipes. CON might work for both. theres also conIN$ and conOUT$. those might also work. if not, i can add a fix in qft itself.

**Comment by TudbuT** [comment]
marking this as resolved due to no answer to my suggested fix
