### ISSUE TITLE
Value for skip/begin parameter

### ISSUE THREAD

**Issue by pepa65** [TudbuT/qft#20]
Quick question:
How do you determine what value to choose for the skip/begin parameter in case of an interrupted transfer? I thought checking the received file, but it seems it is fully allocated, so the file size is the same as on the sending size...

To resume, does the bitrate need to be the same as the aborted transfer, or can it be adjusted (on both sides the same of course)?

**Comment by TudbuT** [comment]
You should still have the log of the original transfer. The log will occasionally tell you how many bytes it has transferred thus far, which is what you'll plug into the skip parameter. ngl I should probably make this more clear or even make it automatic.

**Comment by pepa65** [comment]
The log? You mean the output on the terminal??

**Comment by TudbuT** [comment]
Yes

**Comment by pepa65** [comment]
Terminal output can easily get lost, especially after a power-out/reboot. But I am also not a fan of writing extra log files for every transfer... Unless they get automatically deleted on successful completion..?

So there is no other indication to find out how much was sent/received..?

**Comment by TudbuT** [comment]
Correct, the length used to be an indicator but I switched to file allocation due to less fragmentation and IO slowdowns. I assumed at least one party would be able to remain up.

Temporary files would ofc get deleted upon completion.

**Comment by pepa65** [comment]
OK, thanks!
