### ISSUE TITLE
Make the GUI function an optional feature

### ISSUE THREAD

**Issue by IceCodeNew** [TudbuT/qft#4]
Would you please make the GUI function an optional feature, so that it can be easily disabled through cargo command args?

**Comment by TudbuT** [comment]
I'm currently using a separate branch for this, and the releases have extra versions marked with -nogui. I don't think i can use the cargo feature for this as the gui version has libraries I don't want in the nogui one.

**Comment by IceCodeNew** [comment]
> I'm currently using a separate branch for this, and the releases have extra versions marked with -nogui. I don't think i can use the cargo feature for this as the gui version has libraries I don't want in the nogui one.

I see. Thanks for pointing it out ;-)
