### ISSUE TITLE
Error with qft gui libstdc++-6.dll

### ISSUE THREAD

**Issue by rgabbo** [TudbuT/qft#6]
Using qft with gui in Windows 10 results in an error message that says `libstdc++-6.dll was not found.`

![Senza titolo](https://user-images.githubusercontent.com/58396985/194585439-e25b5893-8eb1-40ef-bb52-95e1e77e16ef.jpg)

**Comment by notsteve82** [comment]
I have the same issue when launching. I tried on many Windows 10 and 11 systems and I cannot find  online where to install  or register those DLLs.

**Comment by TudbuT** [comment]
Thanks a lot for bringing that to my attention! I'll look into it asap.

**Comment by TudbuT** [comment]
Ok, looks like i missed a compiler flag. I'll hotfix that tomorrow.

**Comment by Katzenwerfer** [comment]
It seems like it also requires other DLLs to run.

So far it has asked me for
- libgcc_s_seh-1.dll
- libstdc++-6.dll
- libwinpthread-1.dll

Luckily, I could just copy the ones from my mingw64 installation and was able to succesfully run it.

**Comment by TudbuT** [comment]
Oh that's a lot. Sorry, library management is hellish on windows. Does anyone know how i can approach fixing this? Do I have to use a VM to compile?

**Comment by Katzenwerfer** [comment]
I would assume you just need to do static compilation of the executable. I'm honestly not sure, since I have no expertise on that.

**Comment by SupaGamer2017** [comment]
> Oh that's a lot. Sorry, library management is hellish on windows. Does anyone know how i can approach fixing this? Do I have to use a VM to compile?

No, not really. You shouldn't need a VM to compile. Check your compiler
settings, that might be causing an issue.

(Edit: Fixed formatting - TudbuT)

**Comment by SupaGamer2017** [comment]
Hehe I almost doxxed myself :')

**Comment by TudbuT** [comment]
> No, not really. You shouldn't need a VM to compile. Check your compiler settings, that might be causing an issue.

Well if you're that good at telling the rust toolchain to link to libraries of a different OS without a VM, do tell me how to do it!

Anyways, I've got a VM running right now and it's compiling as I type this.

**Comment by TudbuT** [comment]
Take a look at the release again, the new binary should work fine!
